//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaMMBo.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=C:\\Program Files\\GaMMBo.Test1\\Catego" +
            "ries.mdf")]
       // public string CategoriesConnectionString
        //{
         //   get
          //  {

        //[global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=C:\\Program Files\\GaMMBo.Test1\\Gammbo" +
         //   "DB.mdf")]
        public string CategoriesConnectionString {
            get {

                return ((string)(this["CategoriesConnectionString"]));
            }
        }


        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
//<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=C:\\Program Files\\GaMMBo.Test1\\Catego" +
            "riesData.mdf;Integrated Security=True;Connect Timeout=30")]
  //      public string CategoriesDataConnectionString
    //    {
      //      get
        //    {
//=======
        //[global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=C:\\Program Files\\GaMMBo.Test1\\Gammbo" +
        //    "DB.mdf;Integrated Security=True;Connect Timeout=30")]
        public string CategoriesDataConnectionString {
            get {
//>>>>>>> 55ec1c9872ec4624593c8fd0274546dcfcff902e
                return ((string)(this["CategoriesDataConnectionString"]));
            }
        }


    }
}
